"""empty message

Revision ID: cfe36a33fca9
Revises: 7f26857099c3
Create Date: 2023-12-11 20:10:34.299968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe36a33fca9'
down_revision: Union[str, None] = '7f26857099c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('project', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('project', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('project_author_id_fkey', 'project', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('project_author_id_fkey', 'project', 'user', ['author_id'], ['id'])
    op.alter_column('project', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('project', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
