"""empty message

Revision ID: 3ddcfa8cf492
Revises: cfe36a33fca9
Create Date: 2023-12-13 14:00:06.407615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ddcfa8cf492'
down_revision: Union[str, None] = 'cfe36a33fca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image_path', sa.String(), nullable=True))
    op.drop_column('user', 'profile_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('user', 'profile_image_path')
    # ### end Alembic commands ###
